# Generated by Django 4.1.4 on 2022-12-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
