---
name: ci
on: push

jobs:
  test-python:
    name: test python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pipenv
      - run: pipenv install --dev -v
      - run: pipenv run mypy .
      - run: pipenv run black --config black.toml --check django101
      - run: pipenv run black --config black.toml --check blog
      - run: pipenv run pylint --enable-all-extensions --fail-under 8 .
      - run: pipenv run python manage.py test
