---
name: ci
on: push

jobs:
  test-python:
    name: test python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
      - run: pip install uv
      - run: uv sync --dev -v
      - run: uv run mypy .
      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run python manage.py test
